url: https://jenipatel.com
title: Jenisha Patel
description: Jenisha Patel Montreal Canada McGill Cisco
nav-links:
  - name: Home/About/Contact
    url: /
  - name: Failures
    url: /fail
  - name: Writing
    url: /writing
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true # automatically set is_post=true for all posts
permalink: /:title
sass:
  style: compressed